# Generated by Django 4.2.23 on 2025-06-29 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
        ('hospital', '0002_hospital_approval_hospital_established_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='license',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='licenses.license'),
        ),
    ]
