# Generated by Django 4.2.23 on 2025-10-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'ordering': ['-created_at'], 'verbose_name': 'License', 'verbose_name_plural': 'Licenses'},
        ),
        migrations.AddField(
            model_name='license',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
