# Generated by Django 4.2.23 on 2025-06-29 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userdetails_id_alter_userdetails_user_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='reporting_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL),
        ),
    ]
