# Generated by Django 4.2.23 on 2025-07-03 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_hospital_license'),
        ('users', '0004_userdetails_reporting_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
    ]
