# Generated by Django 4.2.23 on 2025-07-14 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_userrole_userhospital_alter_userdetails_hospital_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhospital',
            name='user_details',
        ),
        migrations.RemoveField(
            model_name='userrole',
            name='user_details',
        ),
        migrations.AddField(
            model_name='userhospital',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
