# Generated by Django 4.2.23 on 2025-09-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_userdetails_address_alter_userdetails_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ManyToManyField(related_name='users', to='users.role'),
        ),
    ]
