# Generated by Django 4.2.23 on 2025-10-07 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('patient', '0002_remove_patient_contact_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='current_hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_patients', to='hospital.hospital'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospitals',
            field=models.ManyToManyField(blank=True, related_name='patients', to='hospital.hospital'),
        ),
    ]
