# Generated by Django 4.2.23 on 2025-10-02 10:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Address', '0002_rename_address_address_address_line_1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('licenses', '0002_alter_license_options_license_remarks'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=255)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Address.address')),
                ('license', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='licenses.license')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
