# Generated by Django 4.2.23 on 2025-10-06 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctoravailability'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together={('doctor', 'day_of_week', 'start_time', 'end_time')},
        ),
    ]
