# Generated by Django 4.2.23 on 2025-10-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('doctors', '0003_alter_doctoravailability_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='hospitals',
            field=models.ManyToManyField(related_name='doctors', to='hospital.hospital'),
        ),
    ]
