# Generated by Django 4.2.23 on 2025-10-07 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        ('doctors', '0004_doctor_hospitals'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='hospital',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_availabilities', to='hospital.hospital'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailability',
            unique_together={('doctor', 'hospital', 'day_of_week', 'start_time', 'end_time')},
        ),
    ]
